// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.1
// source: trim.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trim_Trim_FullMethodName  = "/pb.Trim/Trim"
	Trim_Trim2_FullMethodName = "/pb.Trim/Trim2"
)

// TrimClient is the client API for Trim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrimClient interface {
	Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error)
	Trim2(ctx context.Context, in *TrimRequest2, opts ...grpc.CallOption) (*TrimResponse2, error)
}

type trimClient struct {
	cc grpc.ClientConnInterface
}

func NewTrimClient(cc grpc.ClientConnInterface) TrimClient {
	return &trimClient{cc}
}

func (c *trimClient) Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrimResponse)
	err := c.cc.Invoke(ctx, Trim_Trim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trimClient) Trim2(ctx context.Context, in *TrimRequest2, opts ...grpc.CallOption) (*TrimResponse2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrimResponse2)
	err := c.cc.Invoke(ctx, Trim_Trim2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrimServer is the server API for Trim service.
// All implementations must embed UnimplementedTrimServer
// for forward compatibility.
type TrimServer interface {
	Trim(context.Context, *TrimRequest) (*TrimResponse, error)
	Trim2(context.Context, *TrimRequest2) (*TrimResponse2, error)
	mustEmbedUnimplementedTrimServer()
}

// UnimplementedTrimServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrimServer struct{}

func (UnimplementedTrimServer) Trim(context.Context, *TrimRequest) (*TrimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trim not implemented")
}
func (UnimplementedTrimServer) Trim2(context.Context, *TrimRequest2) (*TrimResponse2, error) {
	return nil, status.Error(codes.Unimplemented, "method Trim2 not implemented")
}
func (UnimplementedTrimServer) mustEmbedUnimplementedTrimServer() {}
func (UnimplementedTrimServer) testEmbeddedByValue()              {}

// UnsafeTrimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrimServer will
// result in compilation errors.
type UnsafeTrimServer interface {
	mustEmbedUnimplementedTrimServer()
}

func RegisterTrimServer(s grpc.ServiceRegistrar, srv TrimServer) {
	// If the following call panics, it indicates UnimplementedTrimServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trim_ServiceDesc, srv)
}

func _Trim_Trim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrimServer).Trim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trim_Trim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrimServer).Trim(ctx, req.(*TrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trim_Trim2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrimServer).Trim2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trim_Trim2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrimServer).Trim2(ctx, req.(*TrimRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

// Trim_ServiceDesc is the grpc.ServiceDesc for Trim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Trim",
	HandlerType: (*TrimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trim",
			Handler:    _Trim_Trim_Handler,
		},
		{
			MethodName: "Trim2",
			Handler:    _Trim_Trim2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trim.proto",
}
