// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: trim.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	mi := &file_trim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_trim_proto_rawDescGZIP(), []int{0}
}

func (x *TrimRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type TrimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	mi := &file_trim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_trim_proto_rawDescGZIP(), []int{1}
}

func (x *TrimResponse) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type TrimRequest2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           []string               `protobuf:"bytes,1,rep,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimRequest2) Reset() {
	*x = TrimRequest2{}
	mi := &file_trim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest2) ProtoMessage() {}

func (x *TrimRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_trim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest2.ProtoReflect.Descriptor instead.
func (*TrimRequest2) Descriptor() ([]byte, []int) {
	return file_trim_proto_rawDescGZIP(), []int{2}
}

func (x *TrimRequest2) GetStr() []string {
	if x != nil {
		return x.Str
	}
	return nil
}

type TrimResponse2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           []string               `protobuf:"bytes,1,rep,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimResponse2) Reset() {
	*x = TrimResponse2{}
	mi := &file_trim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse2) ProtoMessage() {}

func (x *TrimResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_trim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse2.ProtoReflect.Descriptor instead.
func (*TrimResponse2) Descriptor() ([]byte, []int) {
	return file_trim_proto_rawDescGZIP(), []int{3}
}

func (x *TrimResponse2) GetStr() []string {
	if x != nil {
		return x.Str
	}
	return nil
}

var File_trim_proto protoreflect.FileDescriptor

const file_trim_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trim.proto\x12\x02pb\"\x1f\n" +
	"\vTrimRequest\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\" \n" +
	"\fTrimResponse\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\" \n" +
	"\fTrimRequest2\x12\x10\n" +
	"\x03str\x18\x01 \x03(\tR\x03str\"!\n" +
	"\rTrimResponse2\x12\x10\n" +
	"\x03str\x18\x01 \x03(\tR\x03str2c\n" +
	"\x04Trim\x12+\n" +
	"\x04Trim\x12\x0f.pb.TrimRequest\x1a\x10.pb.TrimResponse\"\x00\x12.\n" +
	"\x05Trim2\x12\x10.pb.TrimRequest2\x1a\x11.pb.TrimResponse2\"\x00B\vZ\taddsrv/pbb\x06proto3"

var (
	file_trim_proto_rawDescOnce sync.Once
	file_trim_proto_rawDescData []byte
)

func file_trim_proto_rawDescGZIP() []byte {
	file_trim_proto_rawDescOnce.Do(func() {
		file_trim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trim_proto_rawDesc), len(file_trim_proto_rawDesc)))
	})
	return file_trim_proto_rawDescData
}

var file_trim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trim_proto_goTypes = []any{
	(*TrimRequest)(nil),   // 0: pb.TrimRequest
	(*TrimResponse)(nil),  // 1: pb.TrimResponse
	(*TrimRequest2)(nil),  // 2: pb.TrimRequest2
	(*TrimResponse2)(nil), // 3: pb.TrimResponse2
}
var file_trim_proto_depIdxs = []int32{
	0, // 0: pb.Trim.Trim:input_type -> pb.TrimRequest
	2, // 1: pb.Trim.Trim2:input_type -> pb.TrimRequest2
	1, // 2: pb.Trim.Trim:output_type -> pb.TrimResponse
	3, // 3: pb.Trim.Trim2:output_type -> pb.TrimResponse2
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trim_proto_init() }
func file_trim_proto_init() {
	if File_trim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trim_proto_rawDesc), len(file_trim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trim_proto_goTypes,
		DependencyIndexes: file_trim_proto_depIdxs,
		MessageInfos:      file_trim_proto_msgTypes,
	}.Build()
	File_trim_proto = out.File
	file_trim_proto_goTypes = nil
	file_trim_proto_depIdxs = nil
}
